#############################################################################
# Makefile for building: univopoly_qt
# Generated by qmake (3.1) (Qt 6.2.3)
# Project:  univopoly_qt.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile univopoly_qt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Isrc/core -Isrc/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = univopoly_qt1.0.0
DISTDIR = /Users/enzo/Desktop/projetp4/univopoly/obj/univopoly_qt1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -F/usr/local/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/qt/main_qt.cpp \
		src/qt/mainWindow.cpp \
		src/qt/extensions/mainView.cpp \
		src/qt/extensions/sideBar.cpp \
		src/qt/extensions/components/mainView/Board_qt.cpp \
		src/qt/extensions/components/mainView/Tile_qt.cpp \
		src/qt/extensions/components/mainView/Lobby.cpp \
		src/qt/extensions/components/sideBar/Controllers.cpp \
		src/qt/extensions/components/sideBar/Dice_qt.cpp \
		src/qt/extensions/components/sideBar/Players.cpp \
		src/qt/extensions/components/sideBar/Player_qt.cpp \
		src/core/Board.cpp \
		src/core/Dice.cpp \
		src/core/Game.cpp \
		src/core/Gare.cpp \
		src/core/Inventory.cpp \
		src/core/Player.cpp \
		src/core/Property.cpp \
		src/core/Tile.cpp moc_mainWindow.cpp \
		moc_mainView.cpp \
		moc_sideBar.cpp \
		moc_Board_qt.cpp \
		moc_Controllers.cpp \
		moc_Players.cpp
OBJECTS       = obj/main_qt.o \
		obj/mainWindow.o \
		obj/mainView.o \
		obj/sideBar.o \
		obj/Board_qt.o \
		obj/Tile_qt.o \
		obj/Lobby.o \
		obj/Controllers.o \
		obj/Dice_qt.o \
		obj/Players.o \
		obj/Player_qt.o \
		obj/Board.o \
		obj/Dice.o \
		obj/Game.o \
		obj/Gare.o \
		obj/Inventory.o \
		obj/Player.o \
		obj/Property.o \
		obj/Tile.o \
		obj/moc_mainWindow.o \
		obj/moc_mainView.o \
		obj/moc_sideBar.o \
		obj/moc_Board_qt.o \
		obj/moc_Controllers.o \
		obj/moc_Players.o
DIST          = README.md \
		img/Univopoly_Board.png \
		img/Univopoly_noshadow.png \
		img/pions.png \
		img/buy.png \
		img/roll_dice.png \
		/usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		univopoly_qt.pro src/qt/mainWindow.h \
		src/qt/extensions/mainView.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/qt/extensions/components/mainView/Lobby.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Dice_qt.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		src/core/Board.h \
		src/core/Dice.h \
		src/core/Game.h \
		src/core/Gare.h \
		src/core/Inventory.h \
		src/core/Player.h \
		src/core/Property.h \
		src/core/Tile.h src/qt/main_qt.cpp \
		src/qt/mainWindow.cpp \
		src/qt/extensions/mainView.cpp \
		src/qt/extensions/sideBar.cpp \
		src/qt/extensions/components/mainView/Board_qt.cpp \
		src/qt/extensions/components/mainView/Tile_qt.cpp \
		src/qt/extensions/components/mainView/Lobby.cpp \
		src/qt/extensions/components/sideBar/Controllers.cpp \
		src/qt/extensions/components/sideBar/Dice_qt.cpp \
		src/qt/extensions/components/sideBar/Players.cpp \
		src/qt/extensions/components/sideBar/Player_qt.cpp \
		src/core/Board.cpp \
		src/core/Dice.cpp \
		src/core/Game.cpp \
		src/core/Gare.cpp \
		src/core/Inventory.cpp \
		src/core/Player.cpp \
		src/core/Property.cpp \
		src/core/Tile.cpp
QMAKE_TARGET  = univopoly_qt
DESTDIR       = 
TARGET        = univopoly_qt

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/enzo/Desktop/projetp4/univopoly/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/enzo/Desktop/projetp4/univopoly/univopoly_qt.pro


include /usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

univopoly_qt:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: univopoly_qt.pro /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		univopoly_qt.pro \
		/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile univopoly_qt.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.2.3_1/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/qt.prf:
/usr/local/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/share/qt/mkspecs/features/resources.prf:
/usr/local/share/qt/mkspecs/features/moc.prf:
/usr/local/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/share/qt/mkspecs/features/uic.prf:
/usr/local/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
univopoly_qt.pro:
/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile univopoly_qt.pro

qmake_all: FORCE


all: Makefile univopoly_qt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/mainWindow.h src/qt/extensions/mainView.h src/qt/extensions/sideBar.h src/qt/extensions/components/mainView/Board_qt.h src/qt/extensions/components/mainView/Tile_qt.h src/qt/extensions/components/mainView/Lobby.h src/qt/extensions/components/sideBar/Controllers.h src/qt/extensions/components/sideBar/Dice_qt.h src/qt/extensions/components/sideBar/Players.h src/qt/extensions/components/sideBar/Player_qt.h src/core/Board.h src/core/Dice.h src/core/Game.h src/core/Gare.h src/core/Inventory.h src/core/Player.h src/core/Property.h src/core/Tile.h $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/main_qt.cpp src/qt/mainWindow.cpp src/qt/extensions/mainView.cpp src/qt/extensions/sideBar.cpp src/qt/extensions/components/mainView/Board_qt.cpp src/qt/extensions/components/mainView/Tile_qt.cpp src/qt/extensions/components/mainView/Lobby.cpp src/qt/extensions/components/sideBar/Controllers.cpp src/qt/extensions/components/sideBar/Dice_qt.cpp src/qt/extensions/components/sideBar/Players.cpp src/qt/extensions/components/sideBar/Player_qt.cpp src/core/Board.cpp src/core/Dice.cpp src/core/Game.cpp src/core/Gare.cpp src/core/Inventory.cpp src/core/Player.cpp src/core/Property.cpp src/core/Tile.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainWindow.cpp moc_mainView.cpp moc_sideBar.cpp moc_Board_qt.cpp moc_Controllers.cpp moc_Players.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainWindow.cpp moc_mainView.cpp moc_sideBar.cpp moc_Board_qt.cpp moc_Controllers.cpp moc_Players.cpp
moc_mainWindow.cpp: src/qt/mainWindow.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Dice.h \
		src/core/Gare.h \
		src/qt/extensions/mainView.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/mainWindow.h -o moc_mainWindow.cpp

moc_mainView.cpp: src/qt/extensions/mainView.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/extensions/mainView.h -o moc_mainView.cpp

moc_sideBar.cpp: src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		src/qt/extensions/components/sideBar/Players.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/extensions/sideBar.h -o moc_sideBar.cpp

moc_Board_qt.cpp: src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/extensions/components/mainView/Board_qt.h -o moc_Board_qt.cpp

moc_Controllers.cpp: src/qt/extensions/components/sideBar/Controllers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/extensions/components/sideBar/Controllers.h -o moc_Controllers.cpp

moc_Players.cpp: src/qt/extensions/components/sideBar/Players.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/enzo/Desktop/projetp4/univopoly/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/enzo/Desktop/projetp4/univopoly -I/Users/enzo/Desktop/projetp4/univopoly/src/core -I/Users/enzo/Desktop/projetp4/univopoly/src/qt -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib src/qt/extensions/components/sideBar/Players.h -o moc_Players.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/main_qt.o: src/qt/main_qt.cpp src/qt/mainWindow.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Dice.h \
		src/core/Gare.h \
		src/qt/extensions/mainView.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtGui.framework/Headers/QPalette \
		/usr/local/lib/QtGui.framework/Headers/qpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main_qt.o src/qt/main_qt.cpp

obj/mainWindow.o: src/qt/mainWindow.cpp src/qt/mainWindow.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Dice.h \
		src/core/Gare.h \
		src/qt/extensions/mainView.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindow.o src/qt/mainWindow.cpp

obj/mainView.o: src/qt/extensions/mainView.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		src/qt/extensions/mainView.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainView.o src/qt/extensions/mainView.cpp

obj/sideBar.o: src/qt/extensions/sideBar.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		src/qt/extensions/components/sideBar/Players.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sideBar.o src/qt/extensions/sideBar.cpp

obj/Board_qt.o: src/qt/extensions/components/mainView/Board_qt.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Board_qt.o src/qt/extensions/components/mainView/Board_qt.cpp

obj/Tile_qt.o: src/qt/extensions/components/mainView/Tile_qt.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tile_qt.o src/qt/extensions/components/mainView/Tile_qt.cpp

obj/Lobby.o: src/qt/extensions/components/mainView/Lobby.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Lobby.o src/qt/extensions/components/mainView/Lobby.cpp

obj/Controllers.o: src/qt/extensions/components/sideBar/Controllers.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QIcon \
		/usr/local/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/lib/QtCore.framework/Headers/QDir \
		/usr/local/lib/QtCore.framework/Headers/qdir.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Controllers.o src/qt/extensions/components/sideBar/Controllers.cpp

obj/Dice_qt.o: src/qt/extensions/components/sideBar/Dice_qt.cpp src/qt/extensions/components/sideBar/Dice_qt.h \
		src/core/Dice.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Dice_qt.o src/qt/extensions/components/sideBar/Dice_qt.cpp

obj/Players.o: src/qt/extensions/components/sideBar/Players.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		src/qt/extensions/components/sideBar/Players.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Players.o src/qt/extensions/components/sideBar/Players.cpp

obj/Player_qt.o: src/qt/extensions/components/sideBar/Player_qt.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtGui.framework/Headers/QScreen \
		/usr/local/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtGui.framework/Headers/QWindow \
		/usr/local/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/qvector.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Player_qt.o src/qt/extensions/components/sideBar/Player_qt.cpp

obj/Board.o: src/core/Board.cpp src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Board.o src/core/Board.cpp

obj/Dice.o: src/core/Dice.cpp src/core/Dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Dice.o src/core/Dice.cpp

obj/Game.o: src/core/Game.cpp src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Dice.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Game.o src/core/Game.cpp

obj/Gare.o: src/core/Gare.cpp src/core/Gare.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Gare.o src/core/Gare.cpp

obj/Inventory.o: src/core/Inventory.cpp src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Inventory.o src/core/Inventory.cpp

obj/Player.o: src/core/Player.cpp src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Player.o src/core/Player.cpp

obj/Property.o: src/core/Property.cpp src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Property.o src/core/Property.cpp

obj/Tile.o: src/core/Tile.cpp src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tile.o src/core/Tile.cpp

obj/moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainWindow.o moc_mainWindow.cpp

obj/moc_mainView.o: moc_mainView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainView.o moc_mainView.cpp

obj/moc_sideBar.o: moc_sideBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sideBar.o moc_sideBar.cpp

obj/moc_Board_qt.o: moc_Board_qt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Board_qt.o moc_Board_qt.cpp

obj/moc_Controllers.o: moc_Controllers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Controllers.o moc_Controllers.cpp

obj/moc_Players.o: moc_Players.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Players.o moc_Players.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

