#############################################################################
# Makefile for building: univopoly_qt
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  univopoly_qt.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile univopoly_qt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc/core -Isrc/qt -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = univopoly_qt1.0.0
DISTDIR = /home/nothied/documents/univ/l2/LIFAP4/univopoly/obj/univopoly_qt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/qt/main_qt.cpp \
		src/qt/mainWindow.cpp \
		src/qt/extensions/mainView.cpp \
		src/qt/extensions/sideBar.cpp \
		src/qt/extensions/components/mainView/Board_qt.cpp \
		src/qt/extensions/components/mainView/Tile_qt.cpp \
		src/qt/extensions/components/mainView/Lobby.cpp \
		src/qt/extensions/components/sideBar/Controllers.cpp \
		src/qt/extensions/components/sideBar/Dice_qt.cpp \
		src/qt/extensions/components/sideBar/Players.cpp \
		src/qt/extensions/components/sideBar/Player_qt.cpp \
		src/core/Board.cpp \
		src/core/Dice.cpp \
		src/core/Game.cpp \
		src/core/Gare.cpp \
		src/core/Inventory.cpp \
		src/core/Player.cpp \
		src/core/Property.cpp \
		src/core/Tile.cpp qrc_univopoly_qt.cpp \
		moc_mainWindow.cpp \
		moc_mainView.cpp \
		moc_sideBar.cpp \
		moc_Board_qt.cpp \
		moc_Controllers.cpp \
		moc_Players.cpp
OBJECTS       = obj/main_qt.o \
		obj/mainWindow.o \
		obj/mainView.o \
		obj/sideBar.o \
		obj/Board_qt.o \
		obj/Tile_qt.o \
		obj/Lobby.o \
		obj/Controllers.o \
		obj/Dice_qt.o \
		obj/Players.o \
		obj/Player_qt.o \
		obj/Board.o \
		obj/Dice.o \
		obj/Game.o \
		obj/Gare.o \
		obj/Inventory.o \
		obj/Player.o \
		obj/Property.o \
		obj/Tile.o \
		obj/qrc_univopoly_qt.o \
		obj/moc_mainWindow.o \
		obj/moc_mainView.o \
		obj/moc_sideBar.o \
		obj/moc_Board_qt.o \
		obj/moc_Controllers.o \
		obj/moc_Players.o
DIST          = README.md \
		img/Univopoly_Board.png \
		img/Univopoly_noshadow.png \
		img/pions.png \
		img/buy.png \
		img/roll_dice.png \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		univopoly_qt.pro src/qt/mainWindow.h \
		src/qt/extensions/mainView.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/qt/extensions/components/mainView/Lobby.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Dice_qt.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		src/core/Board.h \
		src/core/Dice.h \
		src/core/Game.h \
		src/core/Gare.h \
		src/core/Inventory.h \
		src/core/Player.h \
		src/core/Property.h \
		src/core/Tile.h src/qt/main_qt.cpp \
		src/qt/mainWindow.cpp \
		src/qt/extensions/mainView.cpp \
		src/qt/extensions/sideBar.cpp \
		src/qt/extensions/components/mainView/Board_qt.cpp \
		src/qt/extensions/components/mainView/Tile_qt.cpp \
		src/qt/extensions/components/mainView/Lobby.cpp \
		src/qt/extensions/components/sideBar/Controllers.cpp \
		src/qt/extensions/components/sideBar/Dice_qt.cpp \
		src/qt/extensions/components/sideBar/Players.cpp \
		src/qt/extensions/components/sideBar/Player_qt.cpp \
		src/core/Board.cpp \
		src/core/Dice.cpp \
		src/core/Game.cpp \
		src/core/Gare.cpp \
		src/core/Inventory.cpp \
		src/core/Player.cpp \
		src/core/Property.cpp \
		src/core/Tile.cpp
QMAKE_TARGET  = univopoly_qt
DESTDIR       = 
TARGET        = univopoly_qt


first: all
####### Build rules

univopoly_qt:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: univopoly_qt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		univopoly_qt.pro \
		univopoly_qt.qrc
	$(QMAKE) -o Makefile univopoly_qt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
univopoly_qt.pro:
univopoly_qt.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile univopoly_qt.pro

qmake_all: FORCE


all: Makefile univopoly_qt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents univopoly_qt.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/mainWindow.h src/qt/extensions/mainView.h src/qt/extensions/sideBar.h src/qt/extensions/components/mainView/Board_qt.h src/qt/extensions/components/mainView/Tile_qt.h src/qt/extensions/components/mainView/Lobby.h src/qt/extensions/components/sideBar/Controllers.h src/qt/extensions/components/sideBar/Dice_qt.h src/qt/extensions/components/sideBar/Players.h src/qt/extensions/components/sideBar/Player_qt.h src/core/Board.h src/core/Dice.h src/core/Game.h src/core/Gare.h src/core/Inventory.h src/core/Player.h src/core/Property.h src/core/Tile.h $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/main_qt.cpp src/qt/mainWindow.cpp src/qt/extensions/mainView.cpp src/qt/extensions/sideBar.cpp src/qt/extensions/components/mainView/Board_qt.cpp src/qt/extensions/components/mainView/Tile_qt.cpp src/qt/extensions/components/mainView/Lobby.cpp src/qt/extensions/components/sideBar/Controllers.cpp src/qt/extensions/components/sideBar/Dice_qt.cpp src/qt/extensions/components/sideBar/Players.cpp src/qt/extensions/components/sideBar/Player_qt.cpp src/core/Board.cpp src/core/Dice.cpp src/core/Game.cpp src/core/Gare.cpp src/core/Inventory.cpp src/core/Player.cpp src/core/Property.cpp src/core/Tile.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_univopoly_qt.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_univopoly_qt.cpp
qrc_univopoly_qt.cpp: univopoly_qt.qrc \
		/usr/lib/qt5/bin/rcc \
		img/player2.png \
		img/player6.png \
		img/buy.png \
		img/player1.png \
		img/player5.png \
		img/player4.png \
		img/player8.png \
		img/player3.png \
		img/player7.png
	/usr/lib/qt5/bin/rcc -name univopoly_qt univopoly_qt.qrc -o qrc_univopoly_qt.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainWindow.cpp moc_mainView.cpp moc_sideBar.cpp moc_Board_qt.cpp moc_Controllers.cpp moc_Players.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainWindow.cpp moc_mainView.cpp moc_sideBar.cpp moc_Board_qt.cpp moc_Controllers.cpp moc_Players.cpp
moc_mainWindow.cpp: src/qt/mainWindow.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Dice.h \
		src/qt/extensions/mainView.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/mainWindow.h -o moc_mainWindow.cpp

moc_mainView.cpp: src/qt/extensions/mainView.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/extensions/mainView.h -o moc_mainView.cpp

moc_sideBar.cpp: src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/extensions/sideBar.h -o moc_sideBar.cpp

moc_Board_qt.cpp: src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/extensions/components/mainView/Board_qt.h -o moc_Board_qt.cpp

moc_Controllers.cpp: src/qt/extensions/components/sideBar/Controllers.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/extensions/components/sideBar/Controllers.h -o moc_Controllers.cpp

moc_Players.cpp: src/qt/extensions/components/sideBar/Players.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/qt/extensions/components/sideBar/Player_qt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nothied/documents/univ/l2/LIFAP4/univopoly/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nothied/documents/univ/l2/LIFAP4/univopoly -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/core -I/home/nothied/documents/univ/l2/LIFAP4/univopoly/src/qt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qt/extensions/components/sideBar/Players.h -o moc_Players.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/main_qt.o: src/qt/main_qt.cpp src/qt/mainWindow.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Dice.h \
		src/qt/extensions/mainView.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main_qt.o src/qt/main_qt.cpp

obj/mainWindow.o: src/qt/mainWindow.cpp src/qt/mainWindow.h \
		src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Dice.h \
		src/qt/extensions/mainView.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/qt/extensions/components/sideBar/Player_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindow.o src/qt/mainWindow.cpp

obj/mainView.o: src/qt/extensions/mainView.cpp src/qt/extensions/mainView.h \
		src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainView.o src/qt/extensions/mainView.cpp

obj/sideBar.o: src/qt/extensions/sideBar.cpp src/qt/extensions/sideBar.h \
		src/qt/extensions/components/sideBar/Controllers.h \
		src/qt/extensions/components/sideBar/Players.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/qt/extensions/components/sideBar/Player_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sideBar.o src/qt/extensions/sideBar.cpp

obj/Board_qt.o: src/qt/extensions/components/mainView/Board_qt.cpp src/qt/extensions/components/mainView/Board_qt.h \
		src/qt/extensions/components/mainView/Tile_qt.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Board.h \
		src/core/Player.h \
		src/core/Inventory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Board_qt.o src/qt/extensions/components/mainView/Board_qt.cpp

obj/Tile_qt.o: src/qt/extensions/components/mainView/Tile_qt.cpp src/qt/extensions/components/mainView/Tile_qt.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tile_qt.o src/qt/extensions/components/mainView/Tile_qt.cpp

obj/Lobby.o: src/qt/extensions/components/mainView/Lobby.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Lobby.o src/qt/extensions/components/mainView/Lobby.cpp

obj/Controllers.o: src/qt/extensions/components/sideBar/Controllers.cpp src/qt/extensions/components/sideBar/Controllers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Controllers.o src/qt/extensions/components/sideBar/Controllers.cpp

obj/Dice_qt.o: src/qt/extensions/components/sideBar/Dice_qt.cpp src/qt/extensions/components/sideBar/Dice_qt.h \
		src/core/Dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Dice_qt.o src/qt/extensions/components/sideBar/Dice_qt.cpp

obj/Players.o: src/qt/extensions/components/sideBar/Players.cpp src/qt/extensions/components/sideBar/Players.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/qt/extensions/components/sideBar/Player_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Players.o src/qt/extensions/components/sideBar/Players.cpp

obj/Player_qt.o: src/qt/extensions/components/sideBar/Player_qt.cpp src/qt/extensions/components/sideBar/Player_qt.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Player_qt.o src/qt/extensions/components/sideBar/Player_qt.cpp

obj/Board.o: src/core/Board.cpp src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Board.o src/core/Board.cpp

obj/Dice.o: src/core/Dice.cpp src/core/Dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Dice.o src/core/Dice.cpp

obj/Game.o: src/core/Game.cpp src/core/Game.h \
		src/core/Board.h \
		src/core/Tile.h \
		src/core/Property.h \
		src/core/Gare.h \
		src/core/Player.h \
		src/core/Inventory.h \
		src/core/Dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Game.o src/core/Game.cpp

obj/Gare.o: src/core/Gare.cpp src/core/Gare.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Gare.o src/core/Gare.cpp

obj/Inventory.o: src/core/Inventory.cpp src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h \
		src/core/Gare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Inventory.o src/core/Inventory.cpp

obj/Player.o: src/core/Player.cpp src/core/Player.h \
		src/core/Inventory.h \
		src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Player.o src/core/Player.cpp

obj/Property.o: src/core/Property.cpp src/core/Property.h \
		src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Property.o src/core/Property.cpp

obj/Tile.o: src/core/Tile.cpp src/core/Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tile.o src/core/Tile.cpp

obj/qrc_univopoly_qt.o: qrc_univopoly_qt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_univopoly_qt.o qrc_univopoly_qt.cpp

obj/moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainWindow.o moc_mainWindow.cpp

obj/moc_mainView.o: moc_mainView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainView.o moc_mainView.cpp

obj/moc_sideBar.o: moc_sideBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sideBar.o moc_sideBar.cpp

obj/moc_Board_qt.o: moc_Board_qt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Board_qt.o moc_Board_qt.cpp

obj/moc_Controllers.o: moc_Controllers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Controllers.o moc_Controllers.cpp

obj/moc_Players.o: moc_Players.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Players.o moc_Players.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

